module.exports = {
  ratingTable: [
    {
      label: 'Very Poor',
      label_cn: '非常差',
      key: 'verypoor',
      textColor: 'text-verypoor-500',
      bgColor: 'bg-verypoor-500',
    },
    {
      label: 'Poor',
      label_cn: '差',
      key: 'poor',
      textColor: 'text-poor-500',
      bgColor: 'bg-poor-500',
    },
    {
      label: 'Fair',
      label_cn: '一般',
      key: 'fair',
      textColor: 'text-fair-500',
      bgColor: 'bg-fair-500',
    },
    {
      label: 'Good',
      label_cn: '好',
      key: 'good',
      textColor: 'text-good-500',
      bgColor: 'bg-good-500',
    },
    {
      label: 'Excellent',
      label_cn: '非常好',
      key: 'excellent',
      textColor: 'text-excellent-500',
      bgColor: 'bg-excellent-500',
    },
  ],
  maxPageCount: 12,
  medicalOrMentalDisorderQuestionList: [
    '107',
    '108',
    '109',
    '110',
    '111',
    '112',
    '114',
    '115',
    '116',
  ],
  chronoType: [
    {
      time: '< 9:00 pm',
      type: 'Definitely Morning',
      type_cn: '早起型',
      bg: 'excellent',
      position: {
        right: '50%',
        bottom: '40px',
        marginRight: '160px',
      },
    },
    {
      time: '9:30 - 10:45 pm',
      type: 'Morning',
      type_cn: '中等程度早起型',
      bg: 'good',
      position: {
        right: '50%',
        top: '60px',
        marginRight: '120px',
      },
    },
    {
      time: '10:45 - 12:45 am',
      type: 'Intermediate',
      type_cn: '中等程度',
      bg: 'fair',
      position: {
        right: '50%',
        top: '10px',
        marginRight: '-80px',
        textAlign: 'center',
        width: '160px',
      },
    },
    {
      time: '12:45 - 2:00 am',
      type: 'Evening',
      type_cn: '中等程度夜间型',
      bg: 'poor',
      position: {
        left: '50%',
        top: '60px',
        marginLeft: '120px',
      },
    },
    {
      time: ' >2:00 am',
      type: 'Definitely Evening',
      type_cn: '绝对熬夜类型',
      bg: 'verypoor',
      position: {
        left: '50%',
        bottom: '40px',
        marginLeft: '160px',
      },
    },
  ],
}
